# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'




- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'ASOCEUDC'
    applications: '63912b7a-bdef-4985-8dda-4c117fd9e2e3'
    scanname: 'DASTTest'
    scantype: 'dynamic'
    dynamicType: 'DAST'
    scanURL: 'https://demo.testfire.net'
    loginMethod: 'Required'
    dynamicuser: 'JSmith'
    dynamicloginpassword: 'Demo1234'
    network: 'public'
    intervention: false
